merapiSim/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('simulation/', include("simulation.urls"))
]

simulation/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = "simulation"
urlpatterns = [
     path("", views.index, name="index"),
	 path("lava", views.lavaSim, name="lavaSim")
]

simulation/models.py
from django.db import models

# Create your models here.

simulation/views.py
from django.http import request, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
import simulation.static.lava.map as mp

# Create your views here.

def index(request):
	return HttpResponse("Landing page goes here")

def lavaSim(request):
	if request.method == 'POST':
		volume = int(request.POST.get('Volume'))
		viskositas = request.POST.get('Viskositas')
		res = doSimulation(volume, viskositas)
		return render(request, 'simulation\lava.html', {
			"map": res
		})
	else:
		return render(request, 'simulation\lava.html', {
			"map": None
		})

def doSimulation(volume, viskositas):
	res = mp.main(volume, viskositas)
	return res

simulation/templates/simulation/lava.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pemetaan lava</title>
    <!-- Bootstrap 4 CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <!-- leaflet css  -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.0/dist/leaflet.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.76.0/dist/L.Control.Locate.min.css" />
    <link rel="stylesheet" href="{% static 'lava/css/Control.FullScreen.css' %}" />
    <link rel="stylesheet" href="{% static 'lava/css/style.css' %}">

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container">
                <a class="navbar-brand font-weight-bold" href="#">Volcano Hazard</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link active px-5" href="#">Home <span
                                class="sr-only">(current)</span></a>
                        <a class="nav-item nav-link px-5" href="#programs">Programs</a>
                        <a class="nav-item nav-link px-5" href="#about">About Us</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <section class="marpad container">
        <h1 class="display-1">lava</h1>
        <p class="lead">
            Lorem Ipsum adalah contoh teks atau dummy dalam industri percetakan dan penataan huruf atau typesetting.
            Lorem Ipsum telah menjadi standar contoh teks sejak tahun 1500an, saat seorang tukang cetak yang tidak
            dikenal mengambil sebuah kumpulan teks dan mengacaknya untuk menjadi sebuah buku contoh huruf. Ia tidak
            hanya bertahan selama 5 abad, tapi juga telah beralih ke penataan huruf elektronik, tanpa ada perubahan
            apapun. Ia mulai dipopulerkan pada tahun 1960 dengan diluncurkannya lembaran-lembaran Letraset yang
            menggunakan kalimat-kalimat dari Lorem Ipsum, dan seiring munculnya perangkat lunak Desktop Publishing
            seperti Aldus PageMaker juga memiliki versi Lorem Ipsum. </p>
            
            <section id="download">
                <div class="marpad container">
                    <div class="name-label">
                        <h2 class="text-center py-2 my-5">Masukan Parameter</h2>
                    </div>
                    <div class="button" style="margin: 0; position: absolute; left: 50%;-ms-transform: translate(-50%, -50%);transform: translate(-50%, -50%);">
                        <form action="{% url 'simulation:lavaSim' %}" method='POST'>
                            {% csrf_token %}
                            <label for="Volume">Volume: </label>
                            <input type="text", name="Volume">
                            <label for="Viskositas">Viskositas: </label>
                            <input type="text", name="Viskositas">
                            <input type="submit" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </section>

        <div class="container marpad">
            {% if map is not none %}
                <img src="{% static 'lava/DIY_result.jpg' %}" alt="Hasil simulasi" style="width: 100%; height: auto;">
            {% else %}
            <p>
                Simulasi belum dilakukan
            </p>
            {% endif %}
        </div>
    </section>




    <!-- Bootstrap Documentation -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
        integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
        crossorigin="anonymous"></script>
</body>

</html>

<!-- leaflet js  -->
<script src="https://unpkg.com/leaflet@1.7.0/dist/leaflet.js"></script>
<script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.76.0/dist/L.Control.Locate.min.js" charset="utf-8"></script>
<script src="{% static 'lava/js/Control.FullScreen.js' %}"></script>
<script src="{% static 'lava/data/persebaran1.js' %}"></script>
<script src="{% static 'lava/data/persebaran2.js' %}"></script>
<script src="{% static 'lava/js/script.js' %}"></script>

simulation/templates/simulation/layout.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
	</head>
	<body>

	</body>
</html>